### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by JakubMatejka** [keboola/ex-ftp#4]
```
CRITICAL: League\Flysystem\FileNotFoundException:File not found at path: _obfuscated_/Payroll_Exports/SuperJournalExport_Monthly_Hourly_20180906.csv {"errFile":"/code/vendor/league/flysystem/src/Filesystem.php","errLine":388,"errCode":0,"errTrace":"
#0 /code/vendor/league/flysystem/src/Filesystem.php(353): League\\Flysystem\\Filesystem->assertPresent('_obfuscated_/Payr...')
#1 /code/vendor/league/flysystem/src/Filesystem.php(366): League\\Flysystem\\Filesystem->getMetadata('_obfuscated_/Payr...')
#2 /code/src/FtpExtractor.php(63): League\\Flysystem\\Filesystem->get('_obfuscated_/Payr...')
#3 /code/src/FtpExtractor.php(52): Keboola\\FtpExtractor\\FtpExtractor->prepareToDownloadFolder('_obfuscated_/Payr...', '/data/out/files...')
#4 /code/src/FtpExtractorComponent.php(26): Keboola\\FtpExtractor\\FtpExtractor->copyFiles('_obfuscated_/Payr...', '/data/out/files...', Object(Keboola\\FtpExtractor\\FileStateRegistry))
#5 /code/src/run.php(14): Keboola\\FtpExtractor\\FtpExtractorComponent->run()
#6 {main}","errPrevious":[hidden]} []
```

viz. `docker-401f703b74ac4560e0416ea669880194`

**Comment by yustme** [comment]
Včera se na tom jeden týpek trápil snad 2 hodiny. Jdu to fixnout.

**Comment by yustme** [comment]
Mergnul jsem to a udělal nový tag.
